version: '3'
networks:
  spotify-refactor-net:
services:
  client:
    build:
      context: client
    container_name: spotify-randomizer-client
    restart: always
    ports: 
      - 3000:3000
    volumes:
      - ./client:/app
    depends_on:
      - api
    networks:
      - spotify-refactor-net
    environment:
      - PROXY_URL=http://spotify-randomizer-api:8888
  api:
    build:
      context: api
    container_name: spotify-randomizer-api
    restart: always
    expose:
      - 8888
    volumes:
      - ./api:/app
    networks:
      - spotify-refactor-net
    environment:
      - DOTENV_TEST_VAL=docker override
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}